config/routes.rb
Rails.application.routes.draw do
  
  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
    end
  end
  resources :roles

  resources :categories do 
    resources :products
  end

  resources :stations do
  end

  resources :addresses do
    collection do
      get :suggestion
    end
  end

  resources :cities

  resources :couriers

  post '/categories/:id', :to => 'categories#recovery'
  post '/categories/:category_id/products/:id', :to => 'products#recovery'

  mount ActionCable.server => '/cable'

  root to: 'stations#index'
end

app/models/station.rb
class Station < ApplicationRecord
	has_one :address, as: :addressable

	has_and_belongs_to_many :couriers

	accepts_nested_attributes_for :address

	belongs_to :city

	def to_s
		self.name
	end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  load_and_authorize_resource

  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = current_city.stations  #此处记得修改
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
    @station.build_address
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params.merge(city: current_city))

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      ret = params.require(:station).permit(:name, address_attributes: [:id, :address, :comment, :lat, :lng])
      ret[:address_attributes].delete(:address) if ret[:address_attributes][:address].blank?
      ret
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.slim
= simple_form_for(@station) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.simple_fields_for :address do |a|
      = a.input :address, as: :select
      = a.input :comment
      = a.input :lat
      = a.input :lng

  .form-actions
    = f.button :submit

javascript:
  $(function(){
    $("#station_address_attributes_address").select2({
      placeholder: "输入一个地址",
      theme: 'bootstrap',
      ajax: {
        url: '/addresses/suggestion.json',
        dataType: 'json',
        delay: 250,
        cache: false
      },
      minimumInputLength: 1
    })

    $("#station_address_attributes_address").on("change", function (e) {
      var data = $("#station_address_attributes_address").select2('data')[0];
      if(data){
        $("#station_address_attributes_lat").val(data['lat'])
        $("#station_address_attributes_lng").val(data['lng'])
      }
    });
  })

app/views/stations/edit.html.slim
h1 Editing station

== render 'form'

=> link_to 'Show', @station
'|
=< link_to 'Back', stations_path

app/views/stations/index.html.slim
.panel.panel-default
  .panel-heading
    | 站点
  .panel-body
    table.table.table-striped
      thead
        tr
          th Name
          th Address
          th Comment
          th Lat
          th Lng
          th
          th
          th

      tbody
        - @stations.each do |station|
          tr
            td = station.name
            td = station.address.address
            td = station.address.comment
            td = station.address.lat
            td = station.address.lng
            td = link_to 'Show', station
            td = link_to 'Edit', edit_station_path(station)
            td = link_to 'Destroy', station, data: { confirm: 'Are you sure?' }, method: :delete
  .panel-footer
    = link_to 'New Station', new_station_path, class: 'btn btn-info btn-sm'

app/views/stations/new.html.slim
h1 New station

== render 'form'

= link_to 'Back', stations_path

app/views/stations/show.html.slim
ol.breadcrumb
  li.active 
    = link_to '站点', stations_path
  li
    = @station.name

.clear
br

.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 基本信息
      .panel-body
        table.table.table-striped
          tr
            td width='35%' Address
            td width='15%' Lat
            td width='15%' Lng
            td width='35%' Comment
          tr
            td width='35%' = @station.address.address
            td width='15%' = @station.address.lat
            td width='15%' = @station.address.lng
            td width='35%' = @station.address.comment

.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 关联取送员
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 名字
          tbody
            - @station.couriers.each do |courier|
              tr
                td 
                  = link_to courier.email, courier

= link_to 'Edit', edit_station_path(@station)
'|
= link_to 'Back', stations_path