config/routes.rb
Rails.application.routes.draw do
  
  devise_for :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
    end
  end
  resources :roles

  resources :categories do 
    resources :products
  end

  resources :stations do
  end

  resources :addresses do
    collection do
      get :suggestion
    end
  end

  resources :cities

  resources :couriers

  post '/categories/:id', :to => 'categories#recovery'
  post '/categories/:category_id/products/:id', :to => 'products#recovery'

  mount ActionCable.server => '/cable'

  root to: 'stations#index'
end

app/views/layouts/_menu.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar

    a.navbar-brand href=""
      ="后台"
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if current_worker
        ul.nav.navbar-nav
          li.dropdown
            = link_to "总部管理 <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', data: {toggle: 'dropdown'}
            ul.dropdown-menu
              - if can?(:manage, Category)
                li class="#{is_active?('categories', params[:controller])}"
                  = link_to "品类", categories_path
              - if can?(:manage, City)
                li class="#{is_active?('cities', params[:controller])}"
                  = link_to "城市", cities_path    
          
          li.dropdown
            = link_to "分城市管理 <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', data: {toggle: 'dropdown'}
            ul.dropdown-menu
              - if can?(:manage, Station)
                li class="#{is_active?('stations', params[:controller])}"
                  = link_to "站点", stations_path
              - if can?(:manage, Courier)
                li class="#{is_active?('couriers', params[:controller])}"
                  = link_to "取送人员", couriers_path

          li.dropdown
            = link_to "系统管理 <b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', data: {toggle: 'dropdown'}
            ul.dropdown-menu
              - if can?(:manage, Worker)
                li class="#{is_active?('workers', params[:controller])}"
                  = link_to "人员", workers_path
              - if can?(:manage, Role)
                li class="#{is_active?('roles', params[:controller])}"
                  = link_to "角色", roles_path

        ul.nav.navbar-nav.ieCss.pull-right role="presentation"
          .dropdown
            span style="font-size:14px; color:#777" = current_worker.email
            button.btn.dropdown-toggler type='button' data-toggle='dropdown' style='background:none' &#9660
            ul.dropdown-menu role='menu' aria-labelledby="dropdownMenu1"
              li role="presentation"
                = link_to "退出登陆", destroy_worker_session_path, method: :delete
        - if current_city
          ul.nav.navbar-nav.ieCss.pull-right role="presentation"
            .dropdown
              span style="font-size:14px; color:#777" = current_city['name']
              button.btn.dropdown-toggler type='button' data-toggle='dropdown' style='background:none' &#9660
              ul.dropdown-menu role='menu' aria-labelledby="dropdownMenu1"
                - current_worker.cities.each do |city|
                  li role="presentation"
                    = link_to city.name, change_current_city_worker_path(current_worker, city_id: city.id), method: :put

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | 后台
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/menu"
    
    .container#container
      = yield